import { Flex, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";

import AboutSection from "../components/AboutSection";
import Footer from "../components/Footer";
import Header from "../components/Header";

const Builder = () => (
  <>
    <Head>
      <title>About the Builder</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Flex
      flexDirection="column"
      justifyContent="center"
      alignItems="center"
      minH="100vh"
    >
      <Header />
      <Heading>About the Builder</Heading>
      <AboutSection
        heading="Background"
        body={
          <Text>
            Jo Rocca is a developer from Orange County, California living in
            Brisbane, Australia. She began her career as a teacher. She has
            taught subjects from English to Science and Digital Technology. Her
            students ranged from ages 3 years old to university students. She
            has lived and worked in the following places: California, New York,
            China, Spain, France, and rural Queensland, and Brisbane, Australia.
            After policy changes in China made her online teaching platform shut
            down over night, she began teaching herself to code, allowing her to
            transition from a career in teaching to a career in web development
            and, in particular, blockchain development.
          </Text>
        }
      />
      <AboutSection
        heading="Professional Experience"
        body={
          <Text>
            Jo Rocca began a formal career in web development as a front-end
            developer in the blockchain space. She currently works at Labrys, a
            blockchain consultancy firm in Brisbane, Australia, as a front-end
            and blockchain developer.
          </Text>
        }
      />
      <AboutSection
        heading="Hobbies and Interests"
        body={
          <Text>
            In her free time, Jo Rocca likes to read books and rewatch Disney
            movies. She is also passionate about languages, and can speak
            English, Spanish, and French fluently, as well as conversational
            Chinese. When she has time and money, she also likes to travel to
            see her family in the United States or visit new and exciting
            places.
          </Text>
        }
      />

      <AboutSection
        heading="Future Goals"
        body={
          <Text>
            Jo Rocca hopes to revive her original goal of building an online
            language-teaching platform, allowing her to combine her skills of
            web development and teaching and her passion for languages. She
            hopes that career transition inspires others, especially women
            seeking to enter male-dominated fields.
          </Text>
        }
      />
      <Footer />
    </Flex>
  </>
);

export default Builder;
